package com.planilla_DAWI.cibertec.Dto;

import com.planilla_DAWI.cibertec.Entity.*;
import jakarta.persistence.Column;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.RequiredArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
@Data
@RequiredArgsConstructor
@AllArgsConstructor
public class PlanillaMensualDTO {
    private Long idPlanillaMensual;
    private Integer anio;
    private Integer mes;
    private Trabajador trabajador;
    private SituacionTrabajador situacion;
    private Cargo cargo;
    private String apellido;
    private String nombre;
    private SistemaPension sistemaPension;
    private EstadoCivil estadoCivil;
    private Short hijos;
    private LocalDateTime fechaIngreso;
    private BigDecimal sueldoBasico;
    private BigDecimal porcHoraExtra1;
    private BigDecimal porcHoraExtra2;
    private BigDecimal porcDescansoTrab;
    private BigDecimal porcFeriadoTrab;
    private BigDecimal PorcAsigFamiliar;
    private BigDecimal nHorasNormal;
    private BigDecimal nHorasExtra1;
    private BigDecimal nHorasExtra2;
    private Short nDiasTrab;
    private Short nDiasDescansos;
    private Short nFeriadosTrab;
    private Short nDescansosTrab;
    private Short nDiasInasistencias;
    private BigDecimal haberBasico;
    private BigDecimal valesEmpleado;
    private BigDecimal vHorasExtra1;
    private BigDecimal vHorasExtra2;
    private BigDecimal vAsigFamiliar;
    private BigDecimal vDescansoTrab;
    private BigDecimal vFeriadoTrab;
    private BigDecimal bonificacionCargo;
    private BigDecimal bonificacionMovilidad;
    private BigDecimal canastaNavidad;
    private BigDecimal escolaridad;
    private BigDecimal diaTrabajador;
    private BigDecimal totalIngreso;
    private BigDecimal renta5ta;
    private BigDecimal descuentoJud1;
    private BigDecimal descuentoJud2;
    private BigDecimal descuentoJud3;
    private BigDecimal otrosAdelantos;
    private BigDecimal adelantoCaja;
    private BigDecimal adelantoQuincena;
    private BigDecimal adelantoVac;
    private BigDecimal adelantoGratificacion;
    private BigDecimal adelantoLiquidacion;
    private BigDecimal adelantoCTS;
    private BigDecimal porcAporte;
    private BigDecimal aporte;
    private BigDecimal porcComision;
    private BigDecimal comision;
    private BigDecimal porcPrima;
    private BigDecimal prima;
    private BigDecimal otdSeg;
    private BigDecimal otdPacifico;
    private Long idBanco1;
    private BigDecimal prestamo1;
    private BigDecimal tardanza;
    private BigDecimal totalDescuento;
    private BigDecimal porcEsSalud;
    private BigDecimal esSalud;
    private BigDecimal accidenteTrab;
    private BigDecimal senati;
    private BigDecimal seguroVidaLey;
    private BigDecimal totalNeto;
    private String totalNetoCad;
    private BigDecimal totalNetoBoleta;
    private String TotalNetoBoletaCad;
    private boolean activo = true;
    private LocalDateTime fecCreacion = LocalDateTime.now();
    private LocalDateTime fecUltimaModificacion;
}
